version: '3.6'

services: 

  # Backend API
  allports-api:
    container_name: backend
    # image: node:8.11.1
    build: ./
    command: npm start
    working_dir: ''

    # connect to postgres service
    environment:
      POSTGRES_USER: Test
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    links:
      - postgres
    ports:
      - "3006:3006"
    volumes:
        - ./:./usr/src/allports-api

  # Postgres
  postgres:
    image: postgres
    ports:
      - "5432:5432"